### ISSUE TITLE
npm start项目起不来是啥子情况

### ISSUE THREAD

**Issue by Wananme** [sunft1996/ant-back#2]
![image](https://user-images.githubusercontent.com/45476748/84801494-d4e6c100-b031-11ea-8b7e-c808dcaad73b.png)
没有其他特殊操作了吧

**Comment by Wananme** [comment]
博主看到了回复下，这么简洁的框架真是太适合我了^V^~~~

**Comment by Wananme** [comment]
博主麻烦帮忙解决一下下，这么简洁的框架真是太适合我了^V^~~~

**Comment by Wananme** [comment]
解决了 博主在前端那里的ssh地址也是后端的。有个小建议，验证码太难识别了，输了十几遍没对，直接把后台验证码判断的代码删了才登陆进去- -！

**Comment by sunft1996** [comment]
> 解决了 博主在前端那里的ssh地址也是后端的。有个小建议，验证码太难识别了，输了十几遍没对，直接把后台验证码判断的代码删了才登陆进去- -！

确实是readme中git clone 的地址写错了，你克隆了后端项目，所以npm start没跑起来。

readme文档已修改。

验证码还好吧~ 我基本上都一遍过
