### ISSUE TITLE
部署后访问登陆界面一直报404错误

### ISSUE THREAD

**Issue by singgett2** [sunft1996/ant-back#7]
请问为什么我把npm run build生成的dist下内容放到apache的html文件夹下之后一直弹404请求错误呀？

**Comment by sunft1996** [comment]
是不是没有部署在域名根目录，`config.js` 添加以下配置试试
```js
base: '/你的路径/',
publicPath: '/你的路径/'
```
具体参考 [ant design pro](https://pro.ant.design/zh-CN/docs/deploy) 部署到非根目录一项

**Comment by sunft1996** [comment]
是不是没有部署在域名根目录，`config.js` 添加以下配置试试
```js
base: '/你的路径/',
publicPath: '/你的路径/'
```
具体参考 [ant design pro](https://pro.ant.design/zh-CN/docs/deploy) 部署到非根目录一项
