### ISSUE TITLE
账户管理

### ISSUE THREAD

**Issue by zhouat** [sunft1996/ant-back#9]
同一个账号，竟然可以多地同时登录。

**Comment by sunft1996** [comment]
自己的项目里面可以限制一下，http://back.1cloud.xyz这个demo网站就不能限制了，不然一个人登录其他人都无法登录访问

**Comment by sunft1996** [comment]
> 同一个账号，竟然可以多地同时登录。

自己的项目里面可以限制一下，http://back.1cloud.xyz 这个demo网站就不能限制了，不然一个人登录其他人都无法登录访问

**Comment by zhouat** [comment]
对框架不熟，这个功能要实现的话，可以给一个示例的patch吗？

**Comment by zhouat** [comment]
.

**Comment by zhouat** [comment]
.
